jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:lcqU9U33f0hzQkRtH1G6oMs=,iv:yQdwYDU8aEEKQmrdBNVPb10GA6hOeDQyp/aRYw6cD3U=,tag:tHR5BCsIIgA/eSJ+FxnTZw==,type:str]
                client_secret: ENC[AES256_GCM,data:HPAfbjiMq9tpAre6x5gZE+joXJdKySohDtunORiLRn267BtRPYmymT59YsBhnHp3wrqil0BQv/l/+j/ou7dm9g==,iv:p/rEpdtw//DQiuJ/66NDwgoLHW5mIvnv9BeaovdAVaE=,tag:9BpL8ly9veaxLZRYP5omgQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:jrwgy+xmyUrBkYy+1cA7Wsmtio1xJ7xBXRffW0vLHlZb31wZmJoYlTp6njij7Ih13eQDItLggorqSV167cZo,iv:qz0tvBs7Wpx6bVZcgfGX5gW7aOYZ0QhZYmhoDqYv1bk=,tag:pGKs2wOvKvmZNguii1GzHw==,type:str]
        extraContainers:
            - name: ENC[AES256_GCM,data:VkPzr9A9cv6wyzgxw82Ys92GqQ==,iv:K89VB2uxwIIdS6BQyp7J+Hy/84teZIKdukVljR1cu5s=,tag:hKznMpPy/6WsLm1myDLLAw==,type:str]
              image: ENC[AES256_GCM,data:h6cj3hU+7xjLNeG4vD2m+2vBzMk7GvMgFMg712zjg7ksJpjxvQw8KzI=,iv:ddX1JcrnYf/Jtl1jfbeebkpXdz31PzD9TqUZg28pA/w=,tag:F2YWp1tKBI0Cs0N5ycb2cg==,type:str]
              volumeMounts:
                - ENC[AES256_GCM,data:NztkyUMD/0hviMceYewFFGf0Y2d5CbE3AD4w40gO02ckGnyzjvNBLbQhL9Vt64f5FpQ=,iv:HEp1AONHGuy36WLM520QVJH01NIt7xpzWgdW/gLVqsY=,tag:7faBJHvCZ55v7uds+eGb5Q==,type:comment]
                - ENC[AES256_GCM,data:+rYMJFHmDcjeYDqIV9UWpCV9dNGQMVNu,iv:AC9F9ZOK+I3kj5ZGIhl92DW3ZefAG5FK71VfMQCcgxg=,tag:Qs+if4DQGk/aM09MLGnhcQ==,type:comment]
                #ENC[AES256_GCM,data:NztkyUMD/0hviMceYewFFGf0Y2d5CbE3AD4w40gO02ckGnyzjvNBLbQhL9Vt64f5FpQ=,iv:HEp1AONHGuy36WLM520QVJH01NIt7xpzWgdW/gLVqsY=,tag:7faBJHvCZ55v7uds+eGb5Q==,type:comment]
                #ENC[AES256_GCM,data:+rYMJFHmDcjeYDqIV9UWpCV9dNGQMVNu,iv:AC9F9ZOK+I3kj5ZGIhl92DW3ZefAG5FK71VfMQCcgxg=,tag:Qs+if4DQGk/aM09MLGnhcQ==,type:comment]
                - name: ENC[AES256_GCM,data:ceQO,iv:LdFGNmDzAoPQ08t9lQbKYEinXL7HQLWQRQl+UG8V3xQ=,tag:qNrM9lEIiaFbQRSi7tBRig==,type:str]
                  mountPath: ENC[AES256_GCM,data:STtbp82euRo3PEMdtdiB,iv:mpZC+nsuZfP9CAYZlrQER99CKBVOXqqaulrihl9hCSA=,tag:j7+VE/lWXPNDGGmrXNrQKA==,type:str]
                - name: ENC[AES256_GCM,data:RgNDfMCd,iv:4zYFIQ+Z3PGwadkwtwoNqQTEr0WNg7kvUhanmHKeAeE=,tag:Ao/oxVbm6FjX5KqNEPRgpg==,type:str]
                  mountPath: ENC[AES256_GCM,data:CebwlNqAHAgWfqQjp4M3MhcMr4dffQ==,iv:AaIxVMxFm3TOs8U5S19LYUNGERsjO4px40xXNLrFvjo=,tag:3JFaa/3UHAKefAaF7xT+EA==,type:str]
              env:
                - name: ENC[AES256_GCM,data:z3ShI/CDTaBj,iv:MQNc5nMV8x+EYjUKkpIY8CLHKwht0UlLsif8HgcQEg8=,tag:QRKnkjhtTRMB1QJklYey5g==,type:str]
                  value: ENC[AES256_GCM,data:g/U2uXw1FG0=,iv:epqlYfx2ZpjYQ03appJSNNmAgerOxXvwb0P3BbjmU/E=,tag:IiY+rEjmoJzFTiCgdrNQNg==,type:str]
                - name: ENC[AES256_GCM,data:K8oy+ZG3sV4XCg==,iv:2YB7p+4JrG4hWfSIG0/i/vlqobUECBhKyJSZ3XqTmu8=,tag:UT+xltXX+sPKHeqVCavIKQ==,type:str]
                  value: ENC[AES256_GCM,data:OElZREl2jtYyzEcH3yofT+ee7QzIozWJGmGGcoz5lOU=,iv:ayBYCBUchqLd4NN2VW/RpKpm5mAnwBAl/rP2woCcIEc=,tag:jXOGJaYhdRGKLgX/6pjAuw==,type:str]
                - name: ENC[AES256_GCM,data:YxSHWRx6ZBmgvkxxDqI=,iv:49HV4bwnjD4S8zvmt+pfX8RGWRMxrZ+f4uACosx7+aY=,tag:yTOd6yUEq7J6hpq4kX4gyQ==,type:str]
                  value: ENC[AES256_GCM,data:ZXYQFP2kHU4=,iv:Mfw7SWRqTqCj73dx6KzXLUOVkBFnv80fgFGvBsjKJ0o=,tag:fIrLbo5fsPPXCbW5i2qtCQ==,type:str]
                - name: ENC[AES256_GCM,data:wAUibkWhwU5pLgOQtlKc,iv:irRQBTuky4Dd5qGDNkNyhBmt3UGafqsqC7jjQsojeuo=,tag:jUNvPpTXJ73HWORkQSYk1w==,type:str]
                  value: ENC[AES256_GCM,data:o5w4ycPriYFFrEwY1ZnWLklP+QS+/SyBh97yj60CiTo=,iv:4PoTAu1feUaHx0SWHWCATGomi+RV3PlbD/g4zTtM7Qw=,tag:WyHjXJtPINicUYal3kiF1w==,type:str]
                - name: ENC[AES256_GCM,data:s2sC9uYrFEdw3o5/giyfnZWQ,iv:xvLwc2lrluqV/fRcIkg5hSnC75jHnnzPsrnnYft3glw=,tag:Wgjv488qzKoPitRDH7aZyw==,type:str]
                  value: ENC[AES256_GCM,data:EyCjiZA3Q/o=,iv:1Ot1Jb2v+bF3DuJ51paORUVQqaJwqMWbZKYCxAz9k8k=,tag:2rR2KlvDgnKv42gObAttMQ==,type:str]
                - name: ENC[AES256_GCM,data:dwl6uMIltPAtJs4yU4SQ/rlaEQ==,iv:H/GZkjiBPxybAEqfxWbm3JsJEaLYiW58VoBBpFVuI7Q=,tag:YqUOJZMSws2+TdrZOkPrww==,type:str]
                  value: ENC[AES256_GCM,data:rErCStPbIULYAvxN/T26rovP1Kq5pFiQVQBTQrHElxs=,iv:yagP0e3Ai5WtDd4fWx2JjJtn1QLq5VXw00FHsUWsIRI=,tag:tQ1xZLvLtSvXCYJW/WIcrA==,type:str]
                - name: ENC[AES256_GCM,data:M1ZTuAAkC0sBcnrZc2MP,iv:5QvFwj6y1M65dzBaMiiH421QoXfdou+8lyLHTRq3Dmw=,tag:Zn4RL9DSTDrehewMNIwklg==,type:str]
                  value: ENC[AES256_GCM,data:jlxjsOBsr+U=,iv:rCxuVqxvZ4rEzGrKilBXPD+Cih7Odovs0mdkjnG7m0c=,tag:+LcvDLYEefPKpfrsMjShLg==,type:str]
                - name: ENC[AES256_GCM,data:OS9NuQfR0vWX32MPn6vOAA==,iv:i25xpkPaPwB5BOITs5Aec9kc6yRVO13gBIW8ZbHCe+U=,tag:B8SuvTl0nopgbP9rlasBIA==,type:str]
                  value: ENC[AES256_GCM,data:nb/cdMIrV/gOtFOATTLkY7DlKS1egl8KzF/uQ3wOJI8=,iv:rHkEi6BKxpJwZSjV4tPAFar1oNO0YD6AhRnFv6i/FvU=,tag:GuKSJdYdU/4x1tz+3GnpXQ==,type:str]
                - name: ENC[AES256_GCM,data:1sFKG/ihhbSdbg8J,iv:SBLsVLrY4g/+j1rOubrj7fh0+zvVAVF4eW8EHZj4FDo=,tag:FYmmfYHRJreKB2GXN3mJwg==,type:str]
                  value: ENC[AES256_GCM,data:9puegBDrGsE=,iv:luSqIX15AiOFIP3OcmfrcjzQPs4wmYa53ddAhNVwOlY=,tag:G1MM+irDHVQRqNH0F+LBRA==,type:str]
                - name: ENC[AES256_GCM,data:u9+gr0jsd5yIo6MpDg==,iv:MItuvZbws5zYS5rbNQxqplXPkttkf0qdf7yiZrxtj9E=,tag:X2fSrT01hHNIVfpuiW6aRA==,type:str]
                  value: ENC[AES256_GCM,data:1vhd2mrcDjD741SaSIwbv2ZkEEXObVEZKJ82rlVk1GI=,iv:1d361D8CRXm5LbE4hqnuRK2ObE/Zzk+HpW3mvgid/VI=,tag:sb9WR2HkawPUlRUkPAxV4w==,type:str]
    custom:
        memory:
            4096M:
                - ENC[AES256_GCM,data:aB8Dv+nuhl3C,iv:2OKEOCEeva1P/L2CGJqsySPpDKzaCZHiP4yeffr7jgc=,tag:lm+3PV4lq/B3GOoB+OKBlg==,type:str]
            1536M:
                - ENC[AES256_GCM,data:TCoacw==,iv:E++/mgFk+Z3kONtcU06iTBOeQZBM0o0uUzp7oTeGhak=,tag:1yhN0uQQ1nBH9agA6PAfPQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:59Z"
          enc: CiQA67O9AIxTFmAaS7Bn4Z7Ajn2VoJZAViDi/WlDGi70sDj5R0wSSQDmhpq8XeOOpmygjHorUvvXdUfujdzf6cSD1IPuz3JUc900UGL5QtXFfLMsfOb2fJrV/h9xhm8Kd1Ub3WF/rSpdG2HuS7kn6PA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-21T20:04:21Z"
    mac: ENC[AES256_GCM,data:msNjOUjJkBVG9fz55byGK3Ln6kdAbSC5dfW2UA79Pof1EwtXp3FO0SLNaAdWNYW/ZTyUwgCBWDHNK9XqAY3ms9nIOFBWvZZcGqUtSBKJ1/RQLfnykpyaKN9WroyybvkL4pX0cjo4Bnxv1dJxcE8BPMoW8XAbzuLqrIxNpqJH+Ts=,iv:6yPXpScK9zlOw0k6hjo92JgP4aDH533DjIPHp7gYMw4=,tag:WX6vYpGqv3NJ1o9+9jezoQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
