jupyterhub-ssh:
  hostKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAF13ir40Ql2urbCCLgVRRBn83NC3PTra0oBkUoOXmwmAAAAJBdHld4XR5X
    eAAAAAtzc2gtZWQyNTUxOQAAACAF13ir40Ql2urbCCLgVRRBn83NC3PTra0oBkUoOXmwmA
    AAAECfd4d5csopEnIrF4+uvKKSHpO5fI12MS7ItOHxcGBtlQXXeKvjRCXa6tsIIuBVFEGf
    zc0Lc9OtrSgGRSg5ebCYAAAACXJ5bG9AeHQ5OQECAwQ=
    -----END OPENSSH PRIVATE KEY-----

jupyterhub:
  hub:
    cookieSecret: 17e7cc4aa29eaa94b00cb22c31ea4495425cf17fa92348930543f1b91a060a0e
  proxy:
    secretToken: d10e48105334cfb96ba6ded6f7730abf8fe05af84b1431fb7901f77be90c4e79

  auth:
    state:
      enabled: True
      cryptoKey: d94220ee6878450ce4f93a6b45259018bcab45b1794b5faab4781142bbe60303
    google:
      # Fill in as needed
      clientId: 639319454093-3dsbfa1qe5a5p12j2a5vjn8miuqcomco.apps.googleusercontent.com
      clientSecret: 5gYamLWb3WcDjoSsHGaSlwrS
      callbackUrl: "https://stat159-staging.datahub.berkeley.edu/hub/oauth_callback"
      loginService: "Calnet ID"
