dependencies:
- appmode==0.9.0
- ipywidgets==8.1.2
- jupyter-archive==3.4.0
- jupyter-resource-usage==1.0.1
- jupyter-server-proxy==4.1.2
- jupyter-rsession-proxy==2.2.0
- jupyterhub==4.0.2
- jupyterlab==4.0.11
- nbgitpuller==1.2.0
- pip:
  - jupyter-shiny-proxy==1.1
